openapi: 3.0.0
info:
  title: API Documentation
  version: '1.0'
servers:
  - url:    http://ec2-3-113-2-184.ap-northeast-1.compute.amazonaws.com/api/v1
    description: HTTP server for the API documentation
paths:
  /auth/signin:
    post:
      summary: signin
      description: This is the API for signing in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            example:
              email: test@example.com
              password: password123
      responses:
        '200':
          description: OK

  /auth/signup:
    post:
      summary: signup
      description: This is the API for signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            example:
              email: test@example.com
              password: password123
      responses:
        '200':
          description: OK
